### ISSUE TITLE
definitelytyped.org

### ISSUE THREAD

**Issue by mattheffernan** [TargetProcess/tauCharts#101]
Getting your project in as a TSD package may really help your exposure and help us that are using typescript. Thanks!

**Comment by vladminsky** [comment]
Hi @mattheffernan,

Do you have any suggestions on how to automatically generate TSD from JSDoc or any annotation?

The only thing I've managed to find is:

https://github.com/Microsoft/TypeScript/issues/2916

but it looks like not much progress with that.

**Comment by mattheffernan** [comment]
@vladminsky that would be a nice feature to re-use the docs.  I'm still getting my feet under me using typescript, since ts and es 6 are so close in syntax it shouldn't take that much to generate the types for it.

**Comment by sblack4** [comment]
I know this is an old thread but I'd love to see the typings too, I'm looking at using a new d3 library for a project at work but need typing definitions

The API looks pretty simple - that's all I really need defined 😸

**Comment by sblack4** [comment]
I've got a minimal definition that works with the 1 minute example,

I've always wanted to contribute a definition to definitively typed so if you don't mind I'll take this issue

I'll see about including the definition at @types/tauCharts

```typescript
interface IChartProps {
    data: any[];
    type:string;
    x:string;
    y:string;
    color:string;
}

declare module tauCharts {
    class Chart{
        constructor(props: IChartProps)
        renderTo(htmlTag: string | HTMLElement): void;
    }
        
}

export = tauCharts;
```

**Comment by alexanderby** [comment]
@sblack4 I've already started writing a type definition, but I can share it only on Monday. It covers basic API, but can be still be useful.

**Comment by sblack4** [comment]
@alexanderby  Cool, I'll let you lead the way then!

have you set up a DefinitelyTyped fork with a typings file for it yet?

**Comment by sblack4** [comment]
@alexanderby  any progress on the typings?

**Comment by alexanderby** [comment]
@sblack4 I can share a d.ts file with you, but it is unfinished (I used React type definition as an example). I didn't push it definitelytyped repository yet and need some time to sort it out. Check it out [here](https://gist.github.com/alexanderby/dc5438065044964006ff2bfb0cc66714).

**Comment by sblack4** [comment]
Thanks @alexanderby , I'll see if I can make some progress

**Comment by alexanderby** [comment]
@sblack4 I've updated the gist, added plugins API, and removed API that is not documented.

**Comment by sblack4** [comment]
Thanks! @alexanderby

**Comment by alexanderby** [comment]
@sblack4 It is now recommended to include `d.ts` into package. So if you have `taucharts` in your `package.json` then auto-completion should work without any effort, just use `import tauCharts from 'taucharts';` (since taucharts@1.2.0).
