### ISSUE TITLE
TypeError: Cannot read property of undefined [after upgrading from v0.5.2 to v0.6.2]

### ISSUE THREAD

**Issue by asaskevich** [TargetProcess/tauCharts#102]
I'm working with the project which uses such frameworks as Require.js/Marionette.js. Recently I upgraded this package to the latest version and tried to render simple composite chart (based on example from documentation: http://jsfiddle.net/7tbjnhbj/4/light/), but it gave me following errors:

\w v0.6.2 (production version):
Screenshot: http://prntscr.com/8u26qw
```js
Uncaught TypeError: Cannot read property 'extractFieldsFormatInfo' of undefined
  Tooltip.plugin._getFormatters @ tauCharts.tooltip.js:379
  Tooltip.plugin.onRender @ tauCharts.tooltip.js:277
  b @ tauCharts.min.js:4
  d.value @ tauCharts.min.js:4
  x.value @ tauCharts.min.js:6
  (anonymous function) @ chart.js:380
  Backbone.Marionette.ItemView.extend.onShow @ main.js:86
  ...
```

\w v0.6.2 (development version):
Screenshot: http://prntscr.com/8u2715
```js
Uncaught TypeError: Cannot read property 'type' of undefined
  createScaleInfo @ tauCharts.js:3982
  (anonymous function) @ tauCharts.js:3075
  createScales @ tauCharts.js:1244
  _drawUnitsStructure @ tauCharts.js:3073
  ...
```

Version 0.6.0 has similar problem, although v0.5.2 works fine.
Here is the bin \w sample which uses old v0.5.2: http://output.jsbin.com/habeza
Here is the updated sample project: https://bitbucket.org/asaskevich/sample

**Comment by vladminsky** [comment]
@asaskevich 

I got this. Looks like an issue in compatibility of tooltip / legend plugin. Will investigate it deeper tomorrow.

And one more question:
Alex, did you solve a problem for requirejs conflict? I believe it is more important problem.

**Comment by asaskevich** [comment]
The problem with require.js appears very randomly and only in real project, so I can't detect reason and reproduce it in my sample (sometimes it brokes full application, sometimes only part of it). Not sure that TauChart causes this error - maybe big number of dependencies cause it. Although problem disappears after commenting usage of the library. Anyway, I'll notify you if I locate the problem with require.js.

One more issue - my real dataset throws one more `undefined` exception with *production* v0.6.2 (http://prntscr.com/8u5f99):
```js
Uncaught TypeError: Cannot read property 'forEach' of undefined
    (anonymous function) @ tauCharts.min.js:10  
    onSpecReady @ tauCharts.min.js:10
    b @ tauCharts.min.js:4
```
This exception impermanent, sometimes it overlaps by `Cannot read property 'type' of undefined`.
I can give real dataset if you need it (settings of the plot are identical to settings of sample project).

**Comment by vladminsky** [comment]
Regarding the error:

```javascript
Cannot read property 'type' of undefined
```

In 0.6.2 release we have to default "text" scale for raw DSL specification:

```javascript
scales: {
    ...
    "text:default":{"type":"value","source":"?"},
    ...
}
```

As well there is an issue with "guide.color" parameter which have to be defaulted to empty object for line, path and area elements to prevent the error:

```javascript
Uncaught TypeError: Cannot read property 'fill' of undefined
```

These issues were fixed for the documentation samples you started from:

http://api.taucharts.com/basic/composite.html


In general pure DSL specification is not stable enough. This week I'm working on "layers" plugin to simplify API for composite charts and avoid using DSL. With the "layers" plugin all issues related to tooltip and legend should be fixed as well.

Let me know if you have any questions.
