### ISSUE TITLE
ReactJS Components

### ISSUE THREAD

**Issue by szahn** [TargetProcess/tauCharts#138]
Is tauCharts compatible with the ReactJS component model? I know in D3, you can just map data to a layout function and get the nodes which can then be rendered to SVG. How would you utilize the power of ReactJS virtual dom with this charting library?

**Comment by Mavrin** [comment]
Hi @szahn. Yes we can use tauCharts with ReactJS. I created simple example https://jsfiddle.net/futqg4ek/1/. But it doesn't use virtaul dom.
```jsx
var chartData = [{
  "team": "d",
  "cycleTime": 1,
  "effort": 1,
  "count": 1,
  "priority": "low"
}, {
  "team": "d",
  "cycleTime": 2,
  "effort": 2,
  "count": 5,
  "priority": "low"
}];

var ReactIgnore = React.createClass({
  displayName: 'ReactIgnore',
  shouldComponentUpdate: function() {
    return false;
  },
  render(){
    return React.Children.only(this.props.children);
  }
});
var TauChart = React.createClass({
 	displayName: 'TauChart',
  componentWillUnmount() {
  		this._chart.destroy();
  },
  componentDidMount() {
  	this._chart = new tauCharts.Chart(Object.assign({}, this.props));
    this._chart.renderTo(this.refs.placeholder);
  },
  render() {
    return (<ReactIgnore><div ref="placeholder"></div></ReactIgnore>)
  }
});
var props = {
    type: 'scatterplot',
    x: 'cycleTime',
    y: 'effort',
    color: 'team',
    size: 'count',
    data: chartData
}

React.render(<TauChart {...props}/>,
  document.getElementById('placeholder')
);
```
For exapmle we have project which use ReactJS for building UI and use tauChart for drawing chart https://vizydrop.com/

**Comment by Semigradsky** [comment]
@szahn, @Mavrin 
Hi! I created wrapper for taucharts if you interested

**Comment by vladminsky** [comment]
Nice work, Dmitry! Thank you!
I will add link to your repository as recommended quick & simple solution for integration Taucharts to React projects.
