### ISSUE TITLE
opendata.by

### ISSUE THREAD

**Issue by nicolaichuk** [TargetProcess/tauCharts#141]
I have heard Vladimir Petriko (vladminsky) speech on "The Rolling Scopes Conference 2016", you may wish to collaborate with the guys who are developing open data in Belarus.

Site github: https://github.com/opendataby/website

Google group: https://groups.google.com/forum/#!forum/opendata-belarus

**Comment by nicolaichuk** [comment]
https://github.com/opendataby/website/issues/9

**Comment by abitrolly** [comment]
We would gladly accept any works that visualize open data that is actual for Belarus. There there are not many people doing such visualizations for the moment. We would also need help to make opendata.by more user friendly for this kind of integrations. Currently it uses Drupal.

**Comment by ushchent** [comment]
Hi there,

Nice tool. This is what I just made with one of our datasets - https://vizydrop.com/shared/drop/56cabb645a7c901000001098?authkey=9465214f8e5186c295d5.

Is there any way to tweak bar sizes and other options like color or axis titles?

Best,
Alexey.

**Comment by alehmr** [comment]
Hi, there

Please find my comments below

>>tweak bar sizes and other options like color 
It is not available for now. Will add in future releases

>>axis titles
Can be changed by clicking on field in axis, so the popup will be shown where you can change the name

Let us know about any questions

**Comment by vladminsky** [comment]
@ushchent Alexey,

In this case X axis is continues time variable. I believe discrete axis is more suitable here. You can tweak it by applying "MONTH" grouping to X axis. This operation should make bar charts look nice.

Thanks,
Vladimir

**Comment by abitrolly** [comment]
@ushchent for comparisons, it is more useful to see them in $$$ using both fixed rate and average rate (or rate at the end of a month).

**Comment by ushchent** [comment]
@vladminsky, @alehmr,

Thanks, now looks much better. Except that I didn't provide full dates, so it shows it for the year 1900. :)
