### ISSUE TITLE
first tick-mark often starts slightly to the right of the x-axis

### ISSUE THREAD

**Issue by jlewis91** [TargetProcess/tauCharts#145]
See: https://jsfiddle.net/ykycn16p/6/

**Comment by vladminsky** [comment]
@jlewis91 

We use native d3.time.scale() for continues time scale. It uses own algorithm to show the most appropriate ticks. It may look weird for some cases. There are not so much points of control over visual look for d3.time and we don't have plans to switch to another solution for time scale.

I will be keep in mind your claim but can't promise we will fix it in near future.

**Comment by jlewis91** [comment]
Thanks for the update. Would it be possible to align the y-axis with the d3.time.scale ticks, not the other way around?

**Comment by vladminsky** [comment]
@jlewis91 

> Would it be possible to align the y-axis with the d3.time.scale ticks, not the other way around?

Sorry I didn't get the question. Can you clarify please once again?

**Comment by jlewis91** [comment]
Sure. You are saying that the issue is that d3.time sets the x-axis tick marks and that d3 cannot be manipulated to align with the y axis limits, but why can't this issue be solved the other way around...i.e. that when autoScale = true, the nearest time-axis tick mark is chosen for the xmin (assuming the date axis is on the x axis)?

**Comment by vladminsky** [comment]
@jlewis91, do you mean something like this?
https://jsfiddle.net/ykycn16p/13/

It can work for some specific cases, but the issue returns once you change container size:
https://jsfiddle.net/ykycn16p/14/

Am I understand you correctly? I don't know good workaround for this.

NOTE: actually "autoScale" is applicable to linear scale only.. at least for now

**Comment by jlewis91** [comment]
yeah, exactly. What about using something like: https://github.com/mbostock/d3/wiki/Time-Scales#nice

**Comment by jlewis91** [comment]
Thank you! :) :+1:

**Comment by vladminsky** [comment]
@jlewis91 

Taucharts gonna apply nice time scale by default. Actually I updated an API notation.. now instead of "autoScale" - use "nice" property. This name is more consistent. Backward compatibility with "autoScale" is saved as well.

The fix will be available in 0.8.1 release.
