### ISSUE TITLE
max / min parameters do not work when there are data points outside of the boundaries

### ISSUE THREAD

**Issue by jlewis91** [TargetProcess/tauCharts#146]
See: https://jsfiddle.net/ykycn16p/7/

**Comment by vladminsky** [comment]
Hi @jlewis91!

In the example provided I see "y" has values from 0 to 10. What behavior you expect when configure chart in such a way?

```javascript
guide: {
    ...
    "y": { min: 4 }
}
```

In my opinion it is not a bug since chart should not ignore data where "y" is below 4. Probably adding a warning console message would help to avoid confusing. What do you think?

**Comment by jlewis91** [comment]
[In ggplot, there's the possibility to zoom with and without clipping:](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf)
<img width="312" alt="screen shot 2016-03-01 at 16 44 54" src="https://cloud.githubusercontent.com/assets/4462211/13432214/fc674fa4-dfcc-11e5-919d-2bfe433549f3.png">

This would take care of a recurring issue for percentage scales in taucharts, where it's impossible to have a clean 0, 100 scale if there is a data point at 100. See this updated example: https://jsfiddle.net/ykycn16p/11/

**Comment by vladminsky** [comment]
@jlewis91 

> where it's impossible to have a clean 0, 100 scale if there is a data point at 100.

Actually it is possible:
https://jsfiddle.net/ykycn16p/12/
(See lines 14-16).
Taucharts adds small margin to actual scale domain by default. Intention is to make axis look more nice. You can switch this off by setting "guide.autoScale" property to false. In this case axis matches exact range of values based on original data. After that you can customize range by setting "guide.min" / "guide.max" properties.

Note that if min/max is higher/lower than actual data range boundaries - it is ignored. See code snippet:
https://github.com/TargetProcess/tauCharts/blob/master/src/scales/linear.js#L22-L25

Do you find this rule confusing? What configuration API would you suggest in this case?

**Comment by vladminsky** [comment]
See also updated documentation on this:
http://api.taucharts.com/basic/guide.html#nice

**Comment by vladminsky** [comment]
0.8.1
