### ISSUE TITLE
new feature: dashed & dotted line types

### ISSUE THREAD

**Issue by jlewis91** [TargetProcess/tauCharts#147]
Just saw [this great graphic](http://www.nytimes.com/interactive/2016/03/01/upshot/super-tuesday-live-republican-delegate-estimates.html) on the New York Times and was hoping it might be possible to reproduce in taucharts.

<img width="978" alt="screen shot 2016-03-02 at 10 05 08" src="https://cloud.githubusercontent.com/assets/4462211/13455564/7ddece90-e05e-11e5-9f96-f25f651d90e5.png">

**Comment by unutranyholas** [comment]
This can be done using CSS. Just redefine basic styles with stroke-dasharray property, like this:
http://jsfiddle.net/03utod2b/

**Comment by jlewis91** [comment]
Thanks!
