### ISSUE TITLE
Problem with usage in es2015 environment

### ISSUE THREAD

**Issue by Semigradsky** [TargetProcess/tauCharts#152]
I tried to repeat [Data Streaming example](http://jsfiddle.net/4o4z6fqn/6/) but got an error:
> tauCharts.js:189 Uncaught Error: [object Object] plugin is not defined

because `plugins` object is empty

My code:
```js
import { api } from 'taucharts';

const chartOptions = {
	...

	plugins: [
		api.plugins.get('trendline')({ showPanel:false })
	]
};
```

Full example here: https://github.com/Semigradsky/taucharts-react-example/blob/master/src/index.js
Demo: http://semigradsky.github.io/taucharts-react-example/

**Comment by Mavrin** [comment]
Hi!
You can use explicit export plugins(recomended)
```js
import trendline from 'taucharts/build/development/plugins/tauCharts.trendline';
const chartOptions = {
    ...

    plugins: [
        trendline({ showPanel:false })
    ]
};
```
or you should register trendline plugin
```js
import 'taucharts/build/development/plugins/tauCharts.trendline';
```
and add section in webpack config
```js
resolve: {
		alias:{
			'tauCharts':'taucharts'
		}
	}
```
Maybe we fix issue with webpack config in next releases.

**Comment by Semigradsky** [comment]
Thanks for the answer! It helped me.

> 
```js
import trendline from 'taucharts/build/development/plugins/tauCharts.trendline';
```

The path looks a little ugly =)

**Comment by Semigradsky** [comment]
Here is what I got, can anyone be helpful.

In `webpack.config.json`:
```js
	resolve: {
		alias: {
			taucharts$: 'taucharts/build/development/tauCharts.js',
			taucharts: 'taucharts/build/development'
		}
	},
```

In code:
```js
...
import TauChart from 'taucharts-react';
import trendline from 'taucharts/plugins/tauCharts.trendline';

import 'taucharts/css/tauCharts.css';
import 'taucharts/plugins/tauCharts.trendline.css';
...
```

**Comment by Mavrin** [comment]
>The path looks a little ugly =)
Yes, it is. 
We have plan to move every plugin in separate package.
