### ISSUE TITLE
Control How Dates show in Tooltip?

### ISSUE THREAD

**Issue by jwang** [TargetProcess/tauCharts#153]
When JS dates are on the same day, the tooltip plugin only shows the date, no time.

https://jsfiddle.net/qfz82nxz/

**Comment by vladminsky** [comment]
Hi @jwang 

Current implementation of tooltip plugin allows to pass "formatters" like in the example below

https://jsfiddle.net/qfz82nxz/1/

A formatter can be a function or string (see d3 time / numeric formats https://github.com/mbostock/d3/wiki/Time-Formatting)

Sorry for delay in response and let me know if you have any questions / ideas?

Also I would appreciate if you share how you use taucharts or leave a short feedback to make the project better?

Thanks in advance!

Vladimir Petriko,
Taucharts crew

**Comment by vladminsky** [comment]
Documentation: http://api.taucharts.com/plugins/tooltip.html#formatters
