### ISSUE TITLE
Possible bug: Cannot read property 'toLowerCase' of undefined(…)

### ISSUE THREAD

**Issue by oliverbienert** [TargetProcess/tauCharts#169]
Hi,
The above error is thrown in `src/unit-domain-period-generator.js`, line **85**. When I set a breakpoint at the row I see that the parameter `periodAlias` is undefined.
This is my config:

```
const chartOptions = {
    type: 'scatterplot',
    x: 'month',
    y: 'cnt',
    size: 'rank',
    guide: {
        x: {
            label: {text: 'Monat', padding: 30, tickPeriod: 'month', tickFormat: 'month'}
        },
        y: {
            label: {text: 'Dokumente', padding: 50}
        }
    },
    dimensions: {
        month: {type : 'order', scale: 'period'},
        cnt: {type : 'measure', scale: 'linear'}
    }
};

```

Wenn I remove the dimensions config, the error disappears, but then my time axis does not get formatted:
2016-04-01T00:00:00Z
but I want:
April 2016

I followed your discussion in previous issue but can't get it to work..

Can you help out?

Changing to last beta version does not help.

Regards Oliver

**Comment by vladminsky** [comment]
Hi, Oliver

It looks like you put "tickPeriod" / "tickFormat" in a wrong place. It should be declared within [guide.x] section directly (not [guide.x.label] as it is currently).

See updated example here: http://jsfiddle.net/dx6L1c9r/

Also I noticed you try to change default paddings for label. Currently there is an issue: you need to disable default layout calculation by set [settings.specEngine = "NONE"] and specify all chart paddings manually.

See live example here: http://jsfiddle.net/ox58hmqe/

Let me know if you have a questions or need additional assistance.

Thank you!

**Comment by vladminsky** [comment]
@oliverbienert 

I forgot to mention that besides discrete periodic scale you can use continues time scale with ticks aligned on months. Use niceInterval property (line 12) and change scale settings to measure / time.

See example: http://jsfiddle.net/pt3pq5o5/

Would be happy to hear that it helped you.

**Comment by oliverbienert** [comment]
Thank you, I didn't see that. My fault. Now it works! No, I need a discrete periodic scale, but thank you for pointing out the `niceInterval` property.
By the way, is there any documentation on how to localize my ticks, say to german? I know, d3 has something like `locale.timeFormat`. How would I use that?

Regards Oliver

**Comment by vladminsky** [comment]
@oliverbienert 

Here is an example: http://jsfiddle.net/v8Lq02qa/ (lines 18 and 27)

In taucharts you can register a formatter by any string key and then use it with [tickFormat] property.
In the example above I register substitute for "%B %Y" string key for russian locale. If I comment line 18 - chart continue to work in default english locale.

I will add a documentation on that.

Let me know if you have another questions.

**Comment by vladminsky** [comment]
I updated documentation:

http://api.taucharts.com/plugins/customticks.html#how-to-add-a-custom-tick-format

Let me know if anything requires additional clarification.

**Comment by oliverbienert** [comment]
Thank you, works like a charm! One small caveat, though: When I make the browser window quite small, x labels appear vertical, which is nice. However, y axis label reads from bottom to top, but the x axis ticks read from top to bottom, so I think it's just a different rotation direction? Would be nice if x ticks could also be read from bottom to top when vertical.
Regards Oliver

**Comment by vladminsky** [comment]
Oliver,

Thanks for a suggestion. I extracted it to a separate issue:

https://github.com/TargetProcess/tauCharts/issues/172
