### ISSUE TITLE
Visual encoding example didn't work

### ISSUE THREAD

**Issue by Semigradsky** [TargetProcess/tauCharts#171]
Custom colors for encoding color value
http://api.taucharts.com/advanced/encoding.html

> tauCharts.min.js:7 Uncaught TypeError: Cannot read property 'memoize' of undefined

**Comment by Mavrin** [comment]
Thank you for notice. Just open example by http http://jsfiddle.net/ojb039vr/2/
We will fix this documentetion issue.
