### ISSUE TITLE
Broken Layers and Dual axis fiddles

### ISSUE THREAD

**Issue by jwang** [TargetProcess/tauCharts#174]
I tried to fix them myself, but I have no idea what's actually changed that broke all of these.

https://blog.taucharts.com/layers-dual-axis/

**Comment by vladminsky** [comment]
Hi @jwang 

The examples are fixed. The issue appears due to fact that we loaded underscorejs from the source which don't support HTTPS while JSFiddle works in HTTPS mode.

Thank you for pointing this out!
