### ISSUE TITLE
tooltip appear on click instead of hover

### ISSUE THREAD

**Issue by icusmiling** [TargetProcess/tauCharts#177]
Good Day,

I's like to be able to have a tooltip open and close on a click event, rather than a hover. Is that a possibility?

Thanks!

**Comment by vladminsky** [comment]
@icusmiling 

Yes, it is possible. For that you need to make custom tooltip plugin based on default one (https://github.com/TargetProcess/tauCharts/blob/master/plugins/tooltip.js).

I will try to give you more details tomorrow (since today I sick and have no access to work environment)

**Comment by icusmiling** [comment]
Thanks, I really appreciate it! Sorry to hear you aren't feeling well, hope you have a speedy recovery!

**Comment by vladminsky** [comment]
Hi @icusmiling 

Here is more details on the topic. I made a quick draft implementation of such a tooltip.

Here is a diff: https://github.com/TargetProcess/tauCharts/pull/178/files

and link to a plugin file itself:

https://github.com/TargetProcess/tauCharts/blob/tooltip-on-click/plugins/tooltip.js

Plugins are not documented yet since api is not stable enough, so ask me any questions you have. I'm happy to help.

**Comment by icusmiling** [comment]
Well, I got it put in, but I'm not seeing any results, Although that's not too surprising, as I wasn't getting the tooltips to show up before either. The legends, quick-filter and trendlines work just fine.

**Comment by vladminsky** [comment]
I made a fiddle for you: https://jsfiddle.net/ac56gkot/

Note lines: 428 and 463. I renamed plugin since re-register plugin is not allowed.

Can I ask you also to tell a few words about a project where you use taucharts?

**Comment by icusmiling** [comment]
Thanks for the JS fiddle, I did manage to get it working, the problem was the charts were part of a popup, and so the tooltips were on a lower z-index and were appearing behind the graph. So currently the pop-ups work great on the bar graphs, but not appearing at all on the scatter plots.

Also, I do get the plugin registered warning in the console, I'm wondering if it's because I'm using multiple graphs.

I'm doing mobile development and this is for displaying information on earthquakes, but I really like using it and I'm planning on using it for other projects in the future.

**Comment by vladminsky** [comment]
@icusmiling 

> not appearing at all on the scatter plots

I somehow missed ELEMENT.POINT from the list of available elements (see line 315): https://jsfiddle.net/ac56gkot/1/

Now custom tooltip works for scatter plot also.

> I do get the plugin registered warning in the console, I'm wondering if it's because I'm using multiple graphs.

Can you please post here the warning? It may appear due to attempt to register the plugin several times. Make sure you declare / include "custom-tooltip" plugin once on the page.

Thanks for sharing your using experience. Don't hesitate to ask questions and post ideas or improvements.

**Comment by icusmiling** [comment]
Fantastic, that fixed it!

> Can you please post here the warning? It may appear due to attempt to register the plugin several times. Make sure you declare / include "custom-tooltip" plugin once on the page.

well, I'm using multiple charts and making function calls to the chart I need:

`function countMag(data) {`
    `var chart = new tauCharts.Chart({`
     `guide: {`
             ` x: { label:{text:"Magnitude"}, nice: false},  // custom label for X axis`
             ` y: { label:{text:"Quantity"}, nice: false},    // custom label for Y axis`
              `color: {`
               ` brewer: {null: '#ccc',green :'#388E3C',yellow: '#FFFF00',orange: '#F57C00', red: '#b71c1c'}`
            `  }`
     `},`
     `settings: {`
     ` fitModel: 'entire-view'`
      `},`
     ` data: data ,`
      `type: 'stacked-bar',`
      `plugins: [`
      `  tauCharts.api.plugins.get('legend')(),`
       ` tauCharts.api.plugins.get('tooltip-custom')({`
         ` fields: ["Location","Date","Latitude","Longitude","Depth","DepthLevel","Magnitude","MagnitudeType","Intensity","Alert","Signifigance","Tsunami"],`
         ` formatters: {`
           ` Depth: {`
             ` label: "Depth",`
              `format: function(n) {`
                `return (n + " km");`
             ` }`
            `},`
           ` DepthLevel: {label: "Depth Scale"},`
           ` MagnitudeType: {label: "Magnitude Type"},`
            `Tsunami: {label: "Tsunami Risk"}`
         ` }`
       ` }),`
       ` tauCharts.api.plugins.get('quick-filter')(["Magnitude","Date", "Latitude", "Longitude", "Depth"]),
      ],`
     ` x: 'Magnitude',`
     ` y: 'Count',`
      `color: 'Alert'`
   `});`
   `chart.renderTo('#chart');`
`}``

So I have a function like this for each chart, so that may be why I'm getting the registered issue, except it occurs on the page load, before any of the functions are called.

Also was getting one other warning:
tauCharts.quick-filter.js:174 -  Uncaught SyntaxError: Invalid or unexpected token
`var compOrder = ['â€™%y',â€ˆ'&thinsp;%b',â€‰'%d', '%H', ':%M', ':%S'];`

> Thanks for sharing your using experience. Don't hesitate to ask questions and post ideas or improvements.

I appreciate you asking, since what I'm working on is for mobile devices, the things off the top of my head relate to that:

- The tooltip boxes sometimes show up off the page, it would be nice to have an option to just center them on the chart, rather than near the element.

- It's nearly impossible to use the quick-filter sliders, be nice to have a larger icon below it that's big enough for touch (I'm working on my own CSS solution for that, I'll share it when I'm done)

**Comment by vladminsky** [comment]
@icusmiling 

> So I have a function like this for each chart, so that may be why I'm getting the registered issue, except it occurs on the page load, before any of the functions are called.

The "countMag" function looks good. It seems you include file with "custom-tooltip" plugin twice somewhere.

> tauCharts.quick-filter.js:174 - Uncaught SyntaxError: Invalid or unexpected token
> var compOrder = ['â€™%y',â€ˆ'&thinsp;%b',â€‰'%d', '%H', ':%M', ':%S'];

I suppose this error is data specific. Can you please reproduce it in JSFiddle?

Thanks for your ideas. I extracted them to a separate issues.

**Comment by icusmiling** [comment]
Regarding "tauCharts.quick-filter.js:174 - Uncaught SyntaxError: Invalid or unexpected token"

Managed to fix this myself, there were 2 parts:
1. needed to include <meta charset="UTF-8"> at the top (duh)
2. changed line 174 in quick-filter.js to:
var compOrder = ['%y','%b','%d',' %H',':%M',':%S'];

and that got rid of the error.

**Comment by vladminsky** [comment]
Excellent @icusmiling ! Thanks for the hint. I will bring it to base version or you can make a pull request.

**Comment by icusmiling** [comment]
You had asked me before where I was using it... Well you can see for yourself now (assuming you are using an android phone, running L or M) 
https://play.google.com/store/apps/details?id=com.tangentapps.geotremor

Thanks for all the assistance! I'll still be using it for other projects, and I still have some refinements to make with this one, but overall, it works fantastic!

**Comment by vladminsky** [comment]
@icusmiling 

Brilliant! It is a big pleasure for me to see taucharts in real work. Can I give a link to GeoTremor as an example of the lib's usage like (https://github.com/TargetProcess/tauCharts#taucharts-examples--usage-reviews)?

**Comment by icusmiling** [comment]
Absolutely! you can use either the link I provided, or my splash page at http://geotremor.tangentapps.com

Thanks!

**Comment by vladminsky** [comment]
@icusmiling, thanks! Added it already (https://github.com/TargetProcess/tauCharts#taucharts-examples--usage-reviews).

The GeoTremor looks pretty interesting while there are some issues I noticed (regarding taucharts):
1) Scatterplot points looks too big. I believe radius was fixed some time ago. Which version of taucharts do you use? Or probably it is a mobile specific (we didn't test it on mobile devices)
2) Unfortunately dynamic filter sometime hangs. Looks like there should be some async layer between range selection and chart refresh.. probably with loading indicator.

Once again I wish you a great success and thank you for the active participation!
