### ISSUE TITLE
Quick filter plugin on mobile

### ISSUE THREAD

**Issue by vladminsky** [TargetProcess/tauCharts#184]
It's nearly impossible to use the quick-filter sliders, be nice to have a larger icon below it that's big enough for touch (I'm working on my own CSS solution for that, I'll share it when I'm done)

(via @icusmiling / https://github.com/TargetProcess/tauCharts/issues/177#issuecomment-225770719)

**Comment by icusmiling** [comment]
I've been playing with this, and I've got something workable, but not all that aesthetically pleasing. Added this to my CSS:
`g .resize rect {`
`    height: 50px;`
`    width:20px;`
`    visibility: visible !important;`
`    fill:#bf360c;`
`    opacity:0.2;`
`}`
``
.graphical-report__filter {
   margin-bottom:30px;
}
``
`.graphical-report__filter__wrap {`
`        padding: 20px 0 10px 14px;`
`        width: 175px;`
`}`

Although a real solution would need some customization of the SVG... will keep playing with it....

**Comment by icusmiling** [comment]
For some reason, when I make changes to the values in the quick-filter.js file, I'm not seeing those changes at all, they are showing as the original values. 

As an example, in this section:
`var svg = d3.select(this._container[dim]).append('svg')`
`                    .attr('width', width + margin.left + margin.right)`
`                    .attr('height', height + margin.top + margin.bottom + 4)`
`                    .append('g')`
`                    .attr('transform', 'translate(' + margin.left + ',' + margin.top + ')');`

changing the last line to `.attr('transform', 'translate(18,0)');` does not affect the code at all, and returns the original value of `translate(12,0)`

Any idea why this is happening?

Thanks!

**Comment by vladminsky** [comment]
@icusmiling 

Do you use development or production (with plugins embedded) assembly? Have you tried to clean cache?
In any case I would recommend you to create new plugin based on the default one and re-register it with new unique name (like "custom-quick-filter"). This way should help to avoid any collisions.

Hope this should help.
