### ISSUE TITLE
Annotation plugin example not working

### ISSUE THREAD

**Issue by c-arnab** [TargetProcess/tauCharts#186]
Annotations example here(https://jsfiddle.net/gfw7bcnp/3/?utm_source=website&utm_medium=embed&utm_campaign=gfw7bcnp) and here(https://blog.taucharts.com/taucharts-0-6-2-area-chart-annotations-export-to-csv-and-themes/#more-128) are not working..

**Comment by vladminsky** [comment]
@c-arnab 

Oh.. that is HTTPs problems in dependencies. I will fix a links while you can try JSFiddle examples via HTTP to make it working right now.

Thanks for notice.

**Comment by vladminsky** [comment]
Examples in the blog post are fixed:

https://blog.taucharts.com/taucharts-0-6-2-area-chart-annotations-export-to-csv-and-themes/
