### ISSUE TITLE
Remove axis and add labels

### ISSUE THREAD

**Issue by c-arnab** [TargetProcess/tauCharts#187]
It would be nice if it was possible to remove the axis from the stacked-chart / horizontal stacked-chart and add labels with the values

**Comment by vladminsky** [comment]
@c-arnab 

Actually "label" encoding in beta now. Here is a JSFiddle:

https://jsfiddle.net/taucharts/qkb2hq9v/

You can explicitly specify "label" as "y" value and hide "y" axis.

Let me know if it is not sufficient for you or you meant something else.

**Comment by c-arnab** [comment]
Cool, why does the label not come on all the columns, is it something to do with 'tickFormat: '.2r''

**Comment by vladminsky** [comment]
@c-arnab 

Can you share a screenshot please?

> 'tickFormat: '.2r
This is just a formatter for a label.

The taucharts has a rules to hide a labels which doesn't fit to bar element. Probably that is root cause..
