### ISSUE TITLE
Streaming example not working in Firefox or Chrome

### ISSUE THREAD

**Issue by gordonbrander** [TargetProcess/tauCharts#199]
The streaming does not seem to work http://jsfiddle.net/4o4z6fqn/6/.

What happens: lines flicker in and out, render for a few pixels, then disappear.
What should happen: a smooth sin wave should be drawn.

This seems to be caused by elements getting blown away mid-way through a CSS transtition. You can see what I mean by reducing the update rate from 200ms to 2000ms.

Tested in Firefox 45.2.0 and Chrome 51.0.2704.103.

**Comment by vladminsky** [comment]
@gordonbrander 

Thanks for the bug report. The issue appeared once we turned on animation by default.
The line is fully redrawn and animated from scratch when scales range is changed (as in example X axis is running). As a result - the lines are flickering.

I've fixed example by turning animation off (see lines 15-17): https://jsfiddle.net/taucharts/qdn76nab/
It seems I need to think on animation improvement as well.

Gordon, I would appreciate if you describe in short what for you use (or consider) taucharts. Is it useful / useless for your tasks? Thanks in advance.
