### ISSUE TITLE
changing the color of axis line, axis label, axis ticks and axis values

### ISSUE THREAD

**Issue by c-arnab** [TargetProcess/tauCharts#200]
I found the cssClass attribute usage here(https://jsfiddle.net/taucharts/7cbthzLu/?utm_source=website&utm_medium=embed&utm_campaign=7cbthzLu) and tried to use it (
.x axis,label {
    stroke: red;
    fill: red;
}) here (https://jsfiddle.net/7cbthzLu/1/) but could not get it working..

**Comment by vladminsky** [comment]
@c-arnab 

Hi! Looks like you missed dot in CSS selector: ".x.axis" instead of ".x axis".

https://jsfiddle.net/taucharts/t2joLdtz/
