### ISSUE TITLE
Box and whiskers chart

### ISSUE THREAD

**Issue by juanjoDiaz** [TargetProcess/tauCharts#204]
Hi guys,

I'm planning to use TauChart for a project and I need to use box and whiskers charts. Or at least have a bar chart where the bar size represent the mean of and add some way to see the standard deviation on top of it.

Is any known way of doing this?

How hard would it be to add this new type of chart to the library? I could try to look into it if it's something that you could be interested.

**Comment by vladminsky** [comment]
Hi @juanjoDiaz 

This is very interesting question indeed. There is no special element for box and whiskers chart in the library but I've managed to create something pretty similar using custom plugin over usual bar chart.

Some comments..
Taucharts is not intended for data processing, so data for the chart should be calculated and prepared in advance (mean, max, min, quantiles) in a form of table which contains quantiles and extremums as a columns (i.e. quantile75, minPrice, maxPrice, etc..)
Then plugin modify an inner element model to bind bottom of the bar to lower quantile.
Then plugin creates in Taucharts specification another thin bar element to map min / max fields.
Also plugin defines point element to encode mean.

I didn't prototype outliers feature. We need to think how to fit them into the data model described.

Note: this is just a quick concept. If it suits your needs - I can assist you on making good API and polish the concept.

https://jsfiddle.net/taucharts/hzkb3n29/

What do you think?

**Comment by juanjoDiaz** [comment]
Hi @vladminsky 

That's exactly what I was looking for! (With some more polishing...) Thank you very much!

I agree that the data should come already processed.

When you say that you would help me on making a good API and polish the concept, do you mean for my own it, or to have it as a plugin or to add it to TauCharts codebase?

**Comment by vladminsky** [comment]
I believe it is good plugin for taucharts. We plan to extract plugins to a separate repo in future but for now let's make it embedded (like https://github.com/TargetProcess/tauCharts/tree/master/plugins). I've already put it here.
Can we collaborate using pull requests from your side and ad-hoc improvements in the core from mine?
I'm not sure if it will be comfortable but let's start in this way and think how to make collaboration efficient. Is it OK for you?

First I propose you to think on good API (configuration settings for a plugin) and data format for outliers (if they are required). Let's discuss.

**Comment by juanjoDiaz** [comment]
@vladminsky,

Sounds good. I've sent you an email.

**Comment by vladminsky** [comment]
@juanjoDiaz 

You can join our public slack and create a dedicated channel: http://slack.taucharts.com/ but if you prefer emails - I like it too.
