### ISSUE TITLE
legend plugins break color brewer

### ISSUE THREAD

**Issue by dusted** [TargetProcess/tauCharts#251]
When using array notation for color brewer and having the legends plugins added the colors are not assigned.

Steps to reproduce

http://jsfiddle.net/taucharts/ayxhavku/?utm_source=website&utm_medium=embed&utm_campaign=ayxhavku

change brewer to  brewer:['#ff0000','rgb(0, 0, 255)','#000']

run the colors will be the default set

remove plugins config section and run the custom colors will be used

**Comment by vladminsky** [comment]
Hi @dusted 

Thanks for a bug report! I will look into.

**Comment by vladminsky** [comment]
Fix will be in next 0.9.5-beta.0 release this week.

**Comment by dusted** [comment]
thanks you

**Comment by keikou** [comment]
I tried the latest version, still has the problem,having the legends plugins added the colors are not assigned.
<script src="https://cdn.jsdelivr.net/d3js/latest/d3.min.js" charset="utf-8"></script>
  <script src="https://cdn.jsdelivr.net/npm/taucharts@2/dist/taucharts.min.js" type="text/javascript"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/taucharts@2/dist/taucharts.min.css">
