### ISSUE TITLE
Page freezes when rendering larger datasets

### ISSUE THREAD

**Issue by TickleThePanda** [TargetProcess/tauCharts#283]
The page freezes when trying to render a dataset with 10,000 entries. With more complex entries, it can take even longer.

Here's some code to reproduce it:
```javascript
setInterval( () => {
    var arr = [];
    var i;
    for(i = 0; i < 10000; i++) {
        arr.push({x:Math.random(), y: Math.random()});
    }
    var chart = new tauCharts.Chart({type: 'scatterplot', x: 'x', y: 'y', data: arr});
    chart.renderTo('#average-day');
}, 0);
```

Chrome gives the warning: `Handling of 'mousewheel' input event was delayed for 1204 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responsive.`

**Comment by vladminsky** [comment]
Hi @TickleThePanda !

Thanks for the request and sorry for delay reply.. I was on vacations.

I just made a performance profile for the example provided and found some obvious bottlenecks which can give significant performance boost (> 10x).
So I'm working on a fix. Will let you when you can expect a fix.
