### ISSUE TITLE
Incorrect tooltip y position after scroll

### ISSUE THREAD

**Issue by adamanthil** [TargetProcess/tauCharts#329]
In beta versions `0.10.0-beta.10` and later the tooltip y position is incorrect after page scroll and is displayed too high. This is not the case on `0.9.x` and `0.10.0-beta.8`

**Comment by alexanderby** [comment]
@adamanthil We have changed tooltip behavior, so that it requires less effort to highlight an element. Now the tooltip is always near cursor.

**Comment by adamanthil** [comment]
In my testing on version `0.10.0-beta.9` and later, after scrolling down the page the tooltip position appears above the cursor by the amount of the scroll. It is only at the cursor when the page has not been scrolled at all.

**Comment by alexanderby** [comment]
@adamanthil The problem is that we use `clientX` and `clientY` mouse event properties instead of `pageX` and `pageY` for getting cursor position. Thanks for the report, we will publish a fix soon.

**Comment by alexanderby** [comment]
@adamanthil Please, check if you problem was solved in `0.10.0-beta.12` version.

**Comment by adamanthil** [comment]
Looks good!
