### ISSUE TITLE
TickMin is always zero even if the value is set above zero

### ISSUE THREAD

**Issue by vinnyscimergent** [TargetProcess/tauCharts#34]
Hi,

I am a new bee to tauChart. I just downloaded and started using the example provided. I tried setting my own data for a line chart . The minimum value what i have provided is above 2500 and also i have set tickMin as 2000 and tickMax as 7000 . But the chart is displayed with the minimum value as 0 . I want to set the minimum value to 2000 or 2k.

Thanks in advance.
Vinny.

**Comment by Mavrin** [comment]
Hi,
Yes it is possible.
Just you shoud set  autoScale as false.
For example http://jsfiddle.net/4o4z6fqn/3/

**Comment by vinnyscimergent** [comment]
Hi Marvin,

It works fine. Thanks.

**Comment by timelyportfolio** [comment]
The docs say setting `autoScale = false` will "exactly fit source domain".  While there are some old examples with `tickMin` and `tickMax` including the fiddle from above, these `tickMin`/`tickMax` seem to have no effect.  Is there a way to arbitrarily set a max/min for the axis?

regarding https://github.com/hrbrmstr/taucharts/issues/12

**Comment by vladminsky** [comment]
@timelyportfolio, try min / max instead of tickMin / tickMax.

It looks like we lost backward compatibility. This should be fixed

**Comment by timelyportfolio** [comment]
`min` / `max` works.  Thanks so much.

**Comment by vladminsky** [comment]
Documentation: http://api.taucharts.com/basic/guide.html#min--max
