### ISSUE TITLE
'order' property is not copied to dimension property

### ISSUE THREAD

**Issue by sergiomedinag** [TargetProcess/tauCharts#36]
When defining a dimension as type 'order', the order property is not copied to the dimension object generated by autoAssignScales.

In the chart below, the order of the legends on 'y' axis do not correspond to the order property:
http://jsfiddle.net/taucharts/5c0pmnj1/light/

**Comment by vladminsky** [comment]
Hi sergiomedinag,

Thanks for pointing this out. Fix is in master branch and will be published with next build.

**Comment by vladminsky** [comment]
release 0.4.0
