### ISSUE TITLE
compiling error from github code

### ISSUE THREAD

**Issue by c-arnab** [TargetProcess/tauCharts#368]
I always have downloaded taucharts from taucharts website download page.
I tried downloading source  from github and compiling the same and recd  errors..

**nodejs command messages..**

Your environment has been set up for using Node.js 4.2.4 (x64) and npm.

C:\Windows\System32>d:

D:\>cd D:\del\dashboard\charting-n\tauCharts-master280317\tauCharts-master

D:\del\dashboard\charting-n\tauCharts-master280317\tauCharts-master>npm install
/
> taucharts@0.10.0-beta.23 prepublish D:\del\dashboard\charting-n\tauCharts-mast
er280317\tauCharts-master
> grunt clean:npmpublish && npm run build

Running "clean:npmpublish" (clean) task
>> 0 paths cleaned.

Done, without errors.

> taucharts@0.10.0-beta.23 build D:\del\dashboard\charting-n\tauCharts-master280
317\tauCharts-master
> bower install && grunt build

bower invalid-meta  for:D:\del\dashboard\charting-n\tauCharts-master280317\tauCh
arts-master\bower.json
bower invalid-meta  The "main" field cannot contain minified files
bower invalid-meta  The "main" field cannot contain minified files
bower not-cached    https://github.com/Mavrin/FileSaver.js.git#*
bower resolve       https://github.com/Mavrin/FileSaver.js.git#*
bower cached        https://github.com/gabelerner/canvg.git#v1.4
bower validate      v1.4 against https://github.com/gabelerner/canvg.git#v1.4
bower cached        https://github.com/askhogan/Modernizr.git#2.8.2
bower validate      2.8.2 against https://github.com/askhogan/Modernizr.git#2.8.
2
bower cached        https://github.com/mbostock-bower/d3-bower.git#3.5.17
bower validate      3.5.17 against https://github.com/mbostock-bower/d3-bower.gi
t#~3.5.5
bower cached        https://github.com/github/fetch.git#0.6.1
bower validate      0.6.1 against https://github.com/github/fetch.git#~0.6.1
bower cached        https://github.com/components/es6-promise.git#2.0.1
bower validate      2.0.1 against https://github.com/components/es6-promise.git#
~2.0.1
bower not-cached    https://github.com/ariutta/rgb-color.git#*
bower resolve       https://github.com/ariutta/rgb-color.git#*
bower download      https://github.com/Mavrin/FileSaver.js/archive/master.tar.gz

bower extract       FileSaver.js#* archive.tar.gz
bower resolved      https://github.com/Mavrin/FileSaver.js.git#2538b41030
bower download      https://github.com/ariutta/rgb-color/archive/master.tar.gz
bower extract       rgb-color#* archive.tar.gz
bower resolved      https://github.com/ariutta/rgb-color.git#ab331e3e52
bower install       canvg#v1.4
bower install       modernizer#2.8.2
bower install       fetch#0.6.1
bower install       d3#3.5.17
bower install       FileSaver.js#2538b41030
bower install       es6-promise#2.0.1
bower install       rgb-color#ab331e3e52

canvg#v1.4 bower_components\canvg
└── rgb-color#ab331e3e52

modernizer#2.8.2 bower_components\modernizer

fetch#0.6.1 bower_components\fetch

d3#3.5.17 bower_components\d3

FileSaver.js#2538b41030 bower_components\FileSaver.js

es6-promise#2.0.1 bower_components\es6-promise

rgb-color#ab331e3e52 bower_components\rgb-color
Running "less:default" (less) task
>> 10 stylesheets created.

Running "less:dark" (less) task
>> 10 stylesheets created.

Running "postcss:dist" (postcss) task
>> 17 processed stylesheets created.

Running "copy:build" (copy) task
Copied 36 files

Running "webpack:build" (webpack) task
Version: webpack 1.12.9
Time: 20229ms

ERROR in ./src/tau.charts.js
Module build failed: Error: Cannot find module 'babel-helper-function-name' (Whi
le processing preset: "D:\\del\\dashboard\\charting-n\\tauCharts-master280317\\t
auCharts-master\\node_modules\\babel-preset-es2015\\lib\\index.js")
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\del\dashboard\charting-n\tauCharts-master280317\ta
uCharts-master\node_modules\babel-preset-es2015\node_modules\babel-plugin-transf
orm-es2015-function-name\lib\index.js:28:32)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\del\dashboard\charting-n\tauCharts-master280317\ta
uCharts-master\node_modules\babel-preset-es2015\lib\index.js:13:47)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
Warning: Task "webpack:build" failed. Use --force to continue.

Aborted due to warnings.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! taucharts@0.10.0-beta.23 build: `bower install && grunt build`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the taucharts@0.10.0-beta.23 build script 'bower install && g
runt build'.
npm ERR! This is most likely a problem with the taucharts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install && grunt build
npm ERR! You can get their info via:
npm ERR!     npm owner ls taucharts
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\del\dashboard\charting-n\tauCharts-master280317\tauCharts-master
\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! taucharts@0.10.0-beta.23 prepublish: `grunt clean:npmpublish && npm run
 build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the taucharts@0.10.0-beta.23 prepublish script 'grunt clean:n
pmpublish && npm run build'.
npm ERR! This is most likely a problem with the taucharts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt clean:npmpublish && npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls taucharts
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\del\dashboard\charting-n\tauCharts-master280317\tauCharts-master
\npm-debug.log

D:\del\dashboard\charting-n\tauCharts-master280317\tauCharts-master>npm run buil
d

> taucharts@0.10.0-beta.23 build D:\del\dashboard\charting-n\tauCharts-master280
317\tauCharts-master
> bower install && grunt build

bower invalid-meta  for:D:\del\dashboard\charting-n\tauCharts-master280317\tauCh
arts-master\bower.json
bower invalid-meta  The "main" field cannot contain minified files
bower invalid-meta  The "main" field cannot contain minified files
Running "less:default" (less) task
>> 10 stylesheets created.

Running "less:dark" (less) task
>> 10 stylesheets created.

Running "postcss:dist" (postcss) task
>> 17 processed stylesheets created.

Running "copy:build" (copy) task
Copied 36 files

Running "webpack:build" (webpack) task
Version: webpack 1.12.9
Time: 1466ms

ERROR in ./src/tau.charts.js
Module build failed: Error: Cannot find module 'babel-helper-function-name' (Whi
le processing preset: "D:\\del\\dashboard\\charting-n\\tauCharts-master280317\\t
auCharts-master\\node_modules\\babel-preset-es2015\\lib\\index.js")
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\del\dashboard\charting-n\tauCharts-master280317\ta
uCharts-master\node_modules\babel-preset-es2015\node_modules\babel-plugin-transf
orm-es2015-function-name\lib\index.js:28:32)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\del\dashboard\charting-n\tauCharts-master280317\ta
uCharts-master\node_modules\babel-preset-es2015\lib\index.js:13:47)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
Warning: Task "webpack:build" failed. Use --force to continue.

Aborted due to warnings.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! taucharts@0.10.0-beta.23 build: `bower install && grunt build`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the taucharts@0.10.0-beta.23 build script 'bower install && g
runt build'.
npm ERR! This is most likely a problem with the taucharts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install && grunt build
npm ERR! You can get their info via:
npm ERR!     npm owner ls taucharts
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\del\dashboard\charting-n\tauCharts-master280317\tauCharts-master
\npm-debug.log

D:\del\dashboard\charting-n\tauCharts-master280317\tauCharts-master>

**npm-debug.log...**

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild taucharts@0.10.0-beta.23
6 info build taucharts@0.10.0-beta.23
7 verbose unsafe-perm in lifecycle true
8 info taucharts@0.10.0-beta.23 Failed to exec build script
9 verbose stack Error: taucharts@0.10.0-beta.23 build: `bower install && grunt build`
9 verbose stack Exit status 3
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid taucharts@0.10.0-beta.23
11 verbose cwd D:\del\dashboard\charting-n\tauCharts-master280317\tauCharts-master
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v4.2.4
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error taucharts@0.10.0-beta.23 build: `bower install && grunt build`
17 error Exit status 3
18 error Failed at the taucharts@0.10.0-beta.23 build script 'bower install && grunt build'.
18 error This is most likely a problem with the taucharts package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     bower install && grunt build
18 error You can get their info via:
18 error     npm owner ls taucharts
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by c-arnab** [comment]
I deleted the entire npm cache and ran npm install again and this time it did the build (dev and prod both)though after that part threw another error and it did not generate npm-debug.log file.

What is the diff between default.min.css and min.css. 
I'm aware that dark.min.css works in dark backgrounds.
Also, what does normalize.min.css do??

Thanks

**Comment by alexanderby** [comment]
@c-arnab Try updating Node.js up to 6.9.1

**Comment by vladminsky** [comment]
@c-arnab 

> Do I no longer need to add underscore.js?
No. Underscore.js is not a required dependency anymore.

> what does normalize.min.css do??
It is obsolete. We keep it for compatibility with old examples.

> What is the diff between default.min.css and min.css.
These files are the same. Just naming convention for themes: default.min.css, dark.min.css etc
Here is an example of dark theme: https://jsfiddle.net/taucharts/s754pqad/
