### ISSUE TITLE
taucharts not loading when used with requireJS optimizer

### ISSUE THREAD

**Issue by patterson** [TargetProcess/tauCharts#381]
I'm using taucharts with requireJS.  It works fine when I load the script at runtime, but when I try to run it through the optimizer and compile them into a single script, it fails.  If I take out taucharts it works.  Is there a known compatibility issue with taucharts and requireJS?  If not, what do I need to do to get this to work with the optimizer?

**Comment by alexanderby** [comment]
Hi. Before I try to help you with RequireJS optimizer, check that paths for taucharts and D3 entries are specified in your RequireJS config:
``` javascript
requirejs.config({
    paths: {
        'taucharts': 'node_modules/taucharts/build/development/tauCharts',
        'd3': 'node_modules/d3/d3'
    }
});
```

**Comment by alexanderby** [comment]
Seems like optimizer couldn't resolve multiple `define()` calls from Taucharts bundle ("tauCharts.js has more than one anonymous define..."). Replacing `define(["d3"]...` with `define('taucharts', ["d3"]...` inside UMD block fixed the issue.

I will think how to reconfigure Webpack bundling.

**Comment by Mavrin** [comment]
Please reopen if issue is actual now.
