### ISSUE TITLE
Refreshing a line chart

### ISSUE THREAD

**Issue by vinnyscimergent** [TargetProcess/tauCharts#39]
Hi !

I am new bee to tauCharts. I have checked my dimensions , data to be visualized and the line chart seems to render perfect as expected. But since i wanted to dynamically add new data to the same chart , It seems to append layout  and the old chart seems not refreshing with new data . As a result of that, div seems to produce scroll.

On checking the elements inside the div , the layout seems to be appended.
I wanted to refresh the data to avoid the scrolling. 

I have used google Chrome browser.

**Comment by vladminsky** [comment]
Hi vinnyscimergent,

If I understand it correctly you want to dynamically change data source on the same chart instance.

There is a [setData] method on chart for this purpose. It accept new data source array and automatically force chart refresh.

I made an example to illustrate the principle: http://jsfiddle.net/4o4z6fqn/4/

Let me know if it help.

Thank you for interest to taucharts!

**Comment by vinnyscimergent** [comment]
Hi vladminsky!,

This is what exactly i wanted. It works fine and helped a lot.
Thanks.
