### ISSUE TITLE
Change Label on change of data:

### ISSUE THREAD

**Issue by vinnyscimergent** [TargetProcess/tauCharts#41]
Hi,

I want to set data and change the label name. Is it possible to change the name of the label of a line chart as well when i try to update my chart using setData()

Thanks in advance.

**Comment by vladminsky** [comment]
It looks like there is no such possibility for now. As a workaround - I would suggest you to cleanup target element and rebuild chart with new specification.

**Comment by vinnyscimergent** [comment]
Hi,

I have figured out a way to change the label name dynamically. Right before setData you can set the name and then set data. 

chart.configGPL.unit.guide.y.label = "Y LABEL DYNAMIC NAME HERE";
chart.setData(data);

This helped.

Please let me know when a functionality is made for this need. 
Thanks @vladminsky

**Comment by vladminsky** [comment]
Hm, my fail.. looks like you found a good way to do this task :)

But instead of "chart.configGPL" I would recommend you to use "chart.getConfig()" method since "configGPL" property is not suppose to be public, while "getConfig()" is an external API method.
