### ISSUE TITLE
Duplicate colors appears when new data is set 

### ISSUE THREAD

**Issue by csbandi** [TargetProcess/tauCharts#462]
**Preset**: "color:var1" has  3 different series of data . Chart was rendered with initial data where 2 set of values of var1 were rendered with 2 different colors
**Action**: Used chart.setData() to update data with three sets of data
**Issue**: Expected chart to display 3 entities with 3 different colors, however one color has been duplicated by 2 entities
Refer to the demo [https://jsfiddle.net/csbandi/52pypg1u/1/](https://jsfiddle.net/csbandi/52pypg1u/1/)
On the demo page, Click on the "Click Me" button and see how blue color is duplicated.
Notice that this works fine when legend is *not* used (comment  - "tauCharts.api.plugins.get('legend')" and retry)

**Comment by alexanderby** [comment]
Hi.
`setData` method seems to be buggy in many cases, because the data is processed when you create a Chart.

We have introduced `updateConfig` method in latest `taucharts@2.0.0-beta.28`, that seems to work stable, you can update chart type, plugins, e.t.c. Use it like:
```javascript
chart.updateConfig(Object.assign({}, initialSpec, {data: [...items]}));
```

See your updated example https://jsfiddle.net/52pypg1u/2/

**Comment by alexanderby** [comment]
To make data update smoothly on chart you should provide `identity` field like
```javascript
const chart = new Taucharts.Chart({
    ...
    identity: 'id',
    ...
});
```
It will make chart understand what elements have changed and not to redraw existing elements.

In some cases you cannot provide identities for data rows. By default identity scale generates ID for each object instance. You can reset rows counter when updating the data:
```javascript
let counter = 0;
chart.updateConfig({
    ...
    settings: {
        refCounter: () => ++counter;
    },
    ...
});
```
https://jsfiddle.net/52pypg1u/10/

If it is not suitable (e.g. some items appear in another category and cannot be animated), it is also possible to generate ID based on JSON. I'm not sure about performance of comparing long strings, but it works https://jsfiddle.net/52pypg1u/11/

**Comment by csbandi** [comment]
Thank you. It worked and I could see updated graph with new data! Could you update the API document with this, it could help folks

**Comment by alexanderby** [comment]
We will update the docs after releasing 2,0,0.
