### ISSUE TITLE
In Chrome, Stacked-Area renders incorrectly after 10 or so data objects.

### ISSUE THREAD

**Issue by weislanes** [TargetProcess/tauCharts#464]
TauCharts seems unable to render more than a couple of points on the X-axis. After that it begins to look like a Picasso painting. 
See the [image](https://i.imgur.com/nKrU8IH.png).
And demo here: https://jsfiddle.net/m2cuovrm.

On Firefox, it works perfectly.

**Comment by alexanderby** [comment]
You have to cast strings to dates https://jsfiddle.net/m2cuovrm/1/

Also you can manually specify the dimensions types https://jsfiddle.net/m2cuovrm/2/

**Comment by weislanes** [comment]
That did it. Thanks, @alexanderby!
