### ISSUE TITLE
Trying to add custom points to line chart

### ISSUE THREAD

**Issue by weislanes** [TargetProcess/tauCharts#465]
Hi,

Really liking this library. Great works. 

I'm struggling with how to add a point to a line chart. I'm measuring stock volume on the Y-axis and Time on the X-axis.

I want to add a circle and colored point (so basically, highlight) whenever volume at the current time is 2% greater than the previous time. I think using transformModel  in a custom plugin is the answer but I can't get this to work. 

Any ideas or documentation? 

Thanks.

**Comment by alexanderby** [comment]
Hi.
Currently we have no documentation for creating complex plugins, so the best source are existing plugins.
Here is an example of a plugin that you described https://jsfiddle.net/52pypg1u/9/

**Comment by weislanes** [comment]
Thanks for taking the time to create this example, @alexanderbyl. Exactly what I needed. 

Appreciated!

**Comment by alexanderby** [comment]
I've added this sample into docs with some explanations https://api.taucharts.com/plugins/create-plugin.html
