### ISSUE TITLE
Any method renders SVG to black figure

### ISSUE THREAD

**Issue by sofeikov** [TargetProcess/tauCharts#489]
I've tried different methods converting obtained SVG to png, including this one:

https://blog.taucharts.com/svg-to-png/

But every time I do this, I get this
![image](https://user-images.githubusercontent.com/6204851/33940200-fafbe874-e005-11e7-8578-1bd4a08c66e4.png)

Is there something special I'm doing right?

**Comment by alexanderby** [comment]
Taucharts use Canvg for converting chart into PNG. You have to pass CSS paths into Export plugin:
```javascript
const chart = new tauCharts.Chart({
    ...
    plugins: [
        tauCharts.api.plugins.get('exportTo')({
            cssPaths: [
                'node_modules/taucharts/build/production/tauCharts.min.css'
            ]
        })
    ]
    ...
});
```

**Comment by sofeikov** [comment]
Thanks, that what i was missing - CSS link..
