### ISSUE TITLE
Changing timezones

### ISSUE THREAD

**Issue by tobyweston** [TargetProcess/tauCharts#512]
Is it possible to change the chart's timezone?

All my data is in UTC and I'd like to switch from the browsers default timezone to a custom one within the webpage and have the chart update. Is that possible?

**Comment by vladminsky** [comment]
@tobyweston 

Taucharts don't have an option to tweak timezone. Try to emulate the required behavior changing input time by a specific timezone offset and use [setData] method to update a chart.

**Comment by tobyweston** [comment]
Thanks
