### ISSUE TITLE
Customize Axes with Tauchart Language

### ISSUE THREAD

**Issue by Waterfront97** [TargetProcess/tauCharts#517]
Hi,

I didn't found in the docs, how it is possible to customize the axis.
For example: I want to display the y axe on the right side

Thanks,
Waterfront

**Comment by Mavrin** [comment]
Yes, it is possible to customize axis. You can set scaleOrient to 'right'. This property is not documented. Other properties which can be customized is documented in https://api.taucharts.com/basic/guide.html
I made example https://jsfiddle.net/taucharts/n9aknof0/15/
