### ISSUE TITLE
npm seems to be missing plugins

### ISSUE THREAD

**Issue by danielmorozoff** [TargetProcess/tauCharts#518]
taucharts were installed with `npm install taucharts`.
Here is the code to load:
```
import * as tCharts from 'taucharts'

let chart = new tCharts.Chart({
              data: self.graphData,
              type: 'scatterplot',
              x: 'extension',
              y: 'num_searches',
              color: 'prefix',
              size: 'num_interactions',
              plugins: [
                  tCharts.api.plugins.get('tooltip')({
                      fields: ['prefix', 'extension', 'num_searches', 'num_interactions']
              })]
})

chart.renderTo('#scatter');
```
Whenever plugins options is included I receive the following error:
`"tooltip" plugin is not defined (anonymous) | @ | taucharts.js?6e40:1 `

When plugins option is excluded the graph loads, but is not styled. 

<img width="720" alt="screen shot 2018-03-31 at 11 53 56 am" src="https://user-images.githubusercontent.com/860203/38164943-3a55e226-34da-11e8-85ae-fe279b5e44f0.png">

This leads me to think the npm installation is either missing or improperly linking the static css?  Is theere a separate npm install I am missing. I tried also installing d3

Has anyone come across this?

Thanks in advance

**Comment by Mavrin** [comment]
If you use module system. You need to export tooltip plugin explicit 
```js
import * as tCharts from 'taucharts'
import tooltip from 'taucharts/dist/plugins/tooltip';

let chart = new tCharts.Chart({
              data: self.graphData,
              type: 'scatterplot',
              x: 'extension',
              y: 'num_searches',
              color: 'prefix',
              size: 'num_interactions',
              plugins: [
                 tooltip({
                      fields: ['prefix', 'extension', 'num_searches', 'num_interactions']
              })]
})

chart.renderTo('#scatter');

```

**Comment by danielmorozoff** [comment]
@Mavrin Thanks this worked and added the tooltip.
I also had to add css explicitly, to get the rendering tow work.
```
import 'taucharts/dist/taucharts.min.css'
import 'taucharts/dist/plugins/tooltip.css'
```
Now it seems the graph is not drawing the x axis labels.

**Comment by danielmorozoff** [comment]
@Mavrin x-axis at small scales does not appear.

Thanks for this. I guess this is not a bug, but it would be nice if we imports were mentioned in the docs.
@Mavrin Thank you for your help
