### ISSUE TITLE
Custom colors and facets

### ISSUE THREAD

**Issue by AdeelK93** [TargetProcess/tauCharts#527]
Is it possible to get custom colors to work with facets? I can get them to work independently, but the colors break when I try the strategy [here](https://api.taucharts.com/advanced/encoding.html#custom-colors-for-encoding-color-value).

Guide appears to be unable to either set a css class or apply custom colors for facets. Thanks!

**Comment by vladminsky** [comment]
@AdeelK93 

See working example here: https://jsfiddle.net/vLjv92ut/
Probably it is not obvious but guide should consists of array in case of facet and color settings are defined in second item (first is dedicated to facet axes). See line 9 in the example provided.

**Comment by AdeelK93** [comment]
Thank you so much, would have never guessed that! Works perfectly
