### ISSUE TITLE
project changelog

### ISSUE THREAD

**Issue by LostKobrakai** [TargetProcess/tauCharts#531]
Is there a [changelog](https://keepachangelog.com/en/1.0.0/) for this project? I could not find any information on that. Also there are 3 different version numbers of the project to be found between what the website is mentioning, the releases here on github and the version published to npm. That's quite confusing.

**Comment by Mavrin** [comment]
Hi @LostKobrakai. 
It is problem. We didn't update documentation for taucharts 2.* . 
We had been keepping changelog in [release page](https://github.com/TargetProcess/tauCharts/releases) for taucharts 1.* .
Unfortunately It is not true for version 2.* .
I hope, we find time and will write changelog and update documentation.
If you are going update tauCharts to 2.*  we have [migration guide] (https://github.com/TargetProcess/tauCharts#migrating-from-taucharts-v1-to-v2)

**Comment by Mavrin** [comment]
fixed. https://github.com/TargetProcess/tauCharts/blob/master/CHANGELOG.md

**Comment by patterson** [comment]
I use bower (I know its outdated) to install components, but it only grabs 1.2.2.  Can you add a new release/tag for 2.3.2?
