### ISSUE TITLE
http://api.taucharts.com/ is down

### ISSUE THREAD

**Issue by abitrolly** [TargetProcess/tauCharts#538]
http://api.taucharts.com/ server not found. No docs.

**Comment by Mavrin** [comment]
Please use https://api.taucharts.com/ . Could you tell me where you found the link without `https`?

**Comment by abitrolly** [comment]
All links from GitHub page including `README.md` and repository description are `http`. Now they work, but it still redirected, so I am not sure that `http` was the reason unless you setup the redirect.

Speaking of `https` also noted that https://taucharts.com/ is marked by Firefox as insecure and not all resources are served over `https`.

![image](https://user-images.githubusercontent.com/8781107/44020965-28c8b9ec-9f16-11e8-94e2-76fdfaabeffc.png)

**Comment by Mavrin** [comment]
@abitrolly, thank you!

**Comment by abitrolly** [comment]
No problem. Awesome project you've got here. :)

**Comment by abitrolly** [comment]
![image](https://user-images.githubusercontent.com/8781107/44032183-fc4826b4-9f38-11e8-80a1-5bcd26e292c1.png)

You may also want to fix this one and turn off Projects and Wiki in https://github.com/TargetProcess/tauCharts/settings
