### ISSUE TITLE
Pre-select series in URL

### ISSUE THREAD

**Issue by OddBloke** [TargetProcess/tauCharts#539]
I have a line graph with a whole bunch of different lines plotted on to it, and the most common way people will use it is to select a few of those lines that they are interested in, using the legend. Once people have selected some lines, it would be great if they could just copy-paste the URL and have other people see the same chart as them.

**Comment by Mavrin** [comment]
It is possible in taucharts@2.5.0. I made some [example](https://mavrin.github.io/taucharts-examples/sync-legend-and-url.html#filter=[%22demo-server%22,%22test-server%22]).
[Code of example](https://github.com/Mavrin/taucharts-examples/blob/master/sync-legend-and-url.js#L124-L157).

**Comment by OddBloke** [comment]
Wow, thanks! This example is almost perfect, the one wrinkle it has is that when a selection is reset, _every_ category is added to the URL, rather than the selections being entirely cleared from the URL.

I do have a list of all the categories (to define an order) which I could compare with to check if that's the situation, but I didn't know if there was a more generic way I could do it from the handler?

**Comment by Mavrin** [comment]
It's a good solution to compare ordered categories and selected categories. Maybe I'll add event type for handler ('reset', 'leave-others', 'focus-single')  in the next version Taucharts.

**Comment by Mavrin** [comment]
@OddBloke  I added event type param in Taucharts 2.6.0. 
```js
Taucharts.api.plugins.get('legend')({
            onSelect({type, selectedCategories}) {
                if(type !== 'reset') {
                    location.hash = 'filter=' + JSON.stringify(selectedCategories);
                } else {
                    location.hash = '';
                }
            },
            selectedCategories: selectedCategories
        })
```
