### ISSUE TITLE
License/documentation clarification

### ISSUE THREAD

**Issue by newzealandpaul** [TargetProcess/tauCharts#54]
The license file in the repo, and on the TauCharts website says it is Apache licensed, but the documentation says this:

"TauCharts is open source framework and it is free for non-commercial use."

( http://api.taucharts.com/tutorials/5min.html )

If it is Apache licensed, then it is free for commercial use as well as non-commercial. The tutorial infers it is only free for non-commercial use. 

Can someone please clarify this in the documentation.

**Comment by Mavrin** [comment]
Hi @newzealandpaul We fixed mistake in tutorial. TauCharts is free for non-commercial and commercial use.
Thank you for notice.
