### ISSUE TITLE
Error loading plugins with RequireJS

### ISSUE THREAD

**Issue by patterson** [TargetProcess/tauCharts#551]
I'm getting the following error when I load the plugins with RequireJS:
![image](https://user-images.githubusercontent.com/168242/45166506-d298d700-b1bc-11e8-9120-b7b666cc5d8c.png)

**Comment by Mavrin** [comment]
@patterson  fixed in release 2.6.1. I made [example](https://mavrin.github.io/taucharts-examples/require-js.html ) with Taucharts and requirejs ([source code](https://github.com/Mavrin/taucharts-examples/blob/master/main.js))

**Comment by patterson** [comment]
Thank you.  I can confirm this did indeed fix the issue I was having.
