### ISSUE TITLE
legend does seem to respect ordered dimensions

### ISSUE THREAD

**Issue by timelyportfolio** [TargetProcess/tauCharts#57]
Excellent work!  It seems based on all the examples I have found on your site and some I have made my own that the `legend` does not respect the `order` provided by an [`ordered dimension`](http://api.taucharts.com/datasource/index.html#-ordered-dimension).  Is this correct?  Would it be potentially something you might add?  Thanks.

**Comment by vladminsky** [comment]
Hi, timelyportfolio

Actually legend plugin was implemented on the early stage as quick solution and it is far from ideal.
We gonna rework it in about 2 releases. It will respect order for sure.

Best regards,
Vladimir

**Comment by timelyportfolio** [comment]
This works now in the reworked legend plugin.  When do you plan to add to master?  Can't wait to use it.  Thanks for fixing so quickly.

**Comment by vladminsky** [comment]
Current code needs some QA. I will make 0.5.2 release next week. It will include legend refactoring as well. Special for you :)

Thanks for using and giving a feedback. It is a source of inspiration :)

**Comment by vladminsky** [comment]
0.5.2
