### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by ignacio82** [TargetProcess/tauCharts#59]
I'm not able to install tauCharts:

    > devtools::install_github("hrbrmstr/taucharts")
    Downloading github repo hrbrmstr/taucharts@master
    Installing taucharts
    '/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
    '/tmp/Rtmp7gjdnh/devtools20762e2bdbf/hrbrmstr-taucharts-ad3e17b' --library='/home/ignacio/R/x86_64-pc-linux-gnu-library/3.2'  \
    --install-tests 
    
    * installing *source* package ‘taucharts’ ...
    ** R
    Error in parse(outFile) : 
      /tmp/Rtmp7gjdnh/devtools20762e2bdbf/hrbrmstr-taucharts-ad3e17b/R/plugins.R:4:1: unexpected input
    3: #' @param tau taucharts object
    4: <<
      ^
      ERROR: unable to collate and parse R files for package ‘taucharts’
    * removing ‘/home/ignacio/R/x86_64-pc-linux-gnu-library/3.2/taucharts’
    Error: Command failed (1)

Thanks!

**Comment by vladminsky** [comment]
Hi @ignacio82,

Looks like you try to install package for R. Please post this issue to @hrbrmstr repository:

https://github.com/hrbrmstr/taucharts

This repo is a javascript charting library on which the R package is built.

**Comment by timelyportfolio** [comment]
@ignacio82 , should be fixed.  Sorry for the problems.
