### ISSUE TITLE
Tooltip fails to show

### ISSUE THREAD

**Issue by baxievski** [TargetProcess/tauCharts#60]
I see it used in the examples at http://www.taucharts.com/, but when I try to use it - it fails to show.

Here's a simple example:
http://jsfiddle.net/62gp6pa9/1/

Best regards

**Comment by vladminsky** [comment]
Hi, @baxievski!

It is known issue. It will be fixed in next 0.5.1 release.

As a workaround - put script tag with taucharts reference at the bottom of the page or inside BODY tag.

Sorry for inconvenience.

Thank you,
Vladimir Petriko

**Comment by baxievski** [comment]
Great, thanks

**Comment by vladminsky** [comment]
Release 0.5.1
