### ISSUE TITLE
Load times slow

### ISSUE THREAD

**Issue by JasonThomasData** [TargetProcess/tauCharts#66]
Hey, just wanted to raise an issue with your examples site itself.
The load times are very slow.
The JSFiddle plugin doesn't seem to be responding.
This page - http://api.taucharts.com/tutorials/5min.html - has loaded for minutes.
It stopped loading and the fiddle has a blank result.

BTW, I live in Australia and our interweb speeds are rubbish, maybe that's it.

**Comment by vladminsky** [comment]
Hi Jason.

Actually our server is in Europe so big distance can be a root cause of slowness. I don't know if we can fix that quickly but anyway thanks for the notice.

**Comment by Mavrin** [comment]
I moved this issue to https://github.com/TargetProcess/taucharts-docs/issues/4.
