### ISSUE TITLE
Provide return value on selected point/points

### ISSUE THREAD

**Issue by happyshows** [TargetProcess/tauCharts#68]
Hi,

I'm wondering if tauCharts.js could provide such api so that hrbrmstr/taucharts could be able to call and fetch the values to R shiny instead of hack.

With this return value it would add more value to interactive analysis on R Shiny (drill down capabilities)

Would you please consider as feature improvement, thanks.

**Comment by vladminsky** [comment]
Hi @happyshows

Currently I'm reworking legend and tooltip plugins to event / data-based approach.

Usage pattern looks like:

```javascript
chart.select((node) => node.config.type === "ELEMENT.POINT")
     .on("click", (dataRow) => ...)
     .on("mouseover", (dataRow) => ...)
     .on("mouseout", (dataRow) => ...)
```

It looks like for drill down capabilities we need to introduce some kind of brushing also.

Do you think it is good enough? Would like to know how you "see" the API.

I'm ready to discuss API. Don't hesitate to share your thoughts on the topic.

**Comment by timelyportfolio** [comment]
@vladminsky I think that would be great.  Ref to the issue on the `R` side. https://github.com/hrbrmstr/taucharts/issues/1.

Here is the little bit of code that I suggested as a hack, but if fails with `tau_legend` since legend removes the elements.  Your solution would solve problems such as these.

```
  d3.select(this.el).selectAll(\'[class^="graphical-report"] .i-role-datum\')[0].forEach(
    function(el){
      el.addEventListener( "click", function(e) {
        alert( "clicked " + JSON.stringify(d3.select(e.target).datum().data) );
      })
    })
```

**Comment by happyshows** [comment]
@vladminsky I won't be the best person to comment on the best implementation details, as I'm more familiar with R than js. @hrbrmstr could provide more valuable input...

**Comment by vladminsky** [comment]
@timelyportfolio & @happyshows 

I got your point guys.

**Comment by vladminsky** [comment]
Shortcut for subscription described above:

```javascript
        var chart = new tauCharts.Chart(cfg);
        chart.renderTo('#target');
        chart.on('elementclick', function (chartRef, e) {
            console.log(e.data);    // data behind an element
            console.log(e.event);   // click event object
            console.log(e.element); // DSL node instance like ELEMENT.POINT
```
The elementclick, elementmouseover, elementmouseout events are supported now

**Comment by timelyportfolio** [comment]
great, look forward to putting it to use.  Thanks so much @vladminsky for your responsiveness and diligence.
