### ISSUE TITLE
Order Of Data Along Axis

### ISSUE THREAD

**Issue by fpcorso** [TargetProcess/tauCharts#77]
Hey Guys! I really like the framework. Very flexible and powerful. However, I am having trouble ordering the data. I am passing an array of objects as my data that is setup something like this:

```
var data = [{
type:'us', count:5, date: 'Wed Sep 2nd'
},
type:'us', count:8, date: 'Thu Sep 3rd'
}]
```

Then, I am passing creating a line graph like this:

```
var Chart = new tauCharts.Chart({
  	guide:{
  	  padding:{l:70, t:10, b:70,r:10},
  	  showGridLines:'xy',
  	  color:{
  		brewer:{
  		  us:'color-us'
  		}
  	  },
  	  y:{
  		label:{
  		  text:'',
  		  padding:50
  		}
  	  },
  	  x:{
  		label:''
  	  }
  	},
  	data: data,
  	type: 'line',
  	x: 'date',
  	y: 'count',
  	color: 'type',
  });
```

The issue is that tauCharts re-arranges my array to make the date alphabetical order. So, the graph shows Thu Sept 3rd before Wed Sep 2nd. I tried to add dimensions using your documentation and setting it like this and then passing a JavaScript Date as the date:

```
dimensions: {
      date    : { type: 'measure', scale: 'time' },
      count     : { type: 'measure' }
    },
```

but then the labels along the X axis are not formatted the way I would like. For example, it says Tue 29, Aug 30, Thu 31, September, Wed 2, Thu 3. I would rather have them all formatted the same way.

Is there not a way to have the labels exactly like the data I am passing through and not re-arrange the date? Alternatively, is there a way to set a standard format when scaling using time?

**Comment by vladminsky** [comment]
Hi @fpcorso,

Line chart attempts to order data by X by default. Looks like we shouldn't do that for ordinal labels. Will fix that in next release.

Currently use workaround by setting "lineOrientation" to "none". This should prevent chart from forcing any ordering:

```javascript
{
   type: 'line',
   lineOrientation: 'none'
}
```

For details on custom formatting look at the following section in the documentation:
http://api.taucharts.com/basic/guide.html#ticks

Thanks for using Taucharts! Share feedback and don't hesitate to ask questions.

**Comment by vladminsky** [comment]
0.6.2
