### ISSUE TITLE
Update config properties after initial load

### ISSUE THREAD

**Issue by mattheffernan** [TargetProcess/tauCharts#86]
How would you for example update the X or Y config values and force a refresh of the chart?

**Comment by vladminsky** [comment]
Hi @mattheffernan 

Once you change chart data - use setData() method. It automatically refresh the chart.

Once you change chart structure or some config settings - rebuild the chart from the ground. To do that - call .destroy() on previous chart instance and create new chart with new config.

At this time only this way. If you have any good thoughts on this - let us know.

**Comment by mattheffernan** [comment]
I found the setData and that works great. I also found the setupConfig(config) function off the Plot class, but when I send the modified config back though then call refresh it doesn't do it. I'm pretty sure it has to do with the rest of the setup stuff that happens in the constructor but haven't had the time to figure the rest out.

Thanks for the tip on the destroy and rebuild, i'll give that a shot. I'll think about the issue and give you some feedback if I can think of something useful.

**Comment by vladminsky** [comment]
@mattheffernan 

The "setupConfig" method is supposed to be an inner method of Plot. Don't try to use it for this purpose.

Will be glad to hear from you.

**Comment by tranquilo** [comment]
Hi there,
Just wanted to add that i wasted some time looking for the setData() method until i found this thread. I think you could display this information on your readme for ease of use.
Btw, i'm using your library to build some livestream charts on node + angular and i must say they are really looking good :) 
cheers

**Comment by vladminsky** [comment]
Thanks for feedback @tranquilo 

I'm working on documentation. Unfortunately, not so quickly as I wish :)

Is your work published somewhere? I would look at.

**Comment by tranquilo** [comment]
I will try to make my angular-tauCharts provider and directive public when i finish this :)

**Comment by mattheffernan** [comment]
SetData is being used in the tests and questions #39 and #41 discuss the SetData method as well.  The code is also pretty straight forward and is well written. Its also all in ES6 so its nice to read.  

Before taking a dependency any lib, you should always read though the tests and source to not only understand what is going on but to ensure its well written. Its the old saying do you want code or documentation, I personally would rather have more code and examples (live examples on something like plunker is ideal) on how to do things than a ton of documentation.

**Comment by tranquilo** [comment]
Come on mate, setData is a pretty important method. Not to be locked in some issue post. This simple method is what makes data live streaming with tauCharts possible and efficient. If you want i can make a commit on the readme.md file showing how to use this and it wouldn't take more than 3 lines.
It's good to go under the hood when you need to, but i can't imagine doing that for every dependency i use on my projects as development time would double.

**Comment by vladminsky** [comment]
Both of you are right! I will improve API transparency in several days. Thanks for discussion :)

**Comment by YenHub** [comment]
> Hi @mattheffernan
> 
> Once you change chart data - use setData() method. It automatically refresh the chart.
> 
> Once you change chart structure or some config settings - rebuild the chart from the ground. To do that - call .destroy() on previous chart instance and create new chart with new config.
> 
> At this time only this way. If you have any good thoughts on this - let us know.

This has saved me HOURS of time!!! 

I am doing exactly this, replacing existing charting wit entirely new configurations which lead to the error `cannot read property 'scrollleft' of null`, therefore, not re-flowing the charts upon resizing the window. 

Thank you, and furthermore; thank you for the awesome project! 

On a separate note... :) 

Are there any plans to overhaul the API documentation at any point soon? 

Currently, it appears the documentation is fragmented across the different releases, with many custom functionality available within the tool still undocumented.

**Comment by Mavrin** [comment]
Hi @YenHub, it is difficult question when we would make documentation better 😞 .
And for your case  in Taucharts 2.* we added `updateConfig` method, which allow change data and configuration together. That method maybe will be useful for your case.
